language: python
sudo: false
python:
  - 3.6
  - 3.7

#
#install:
#  - pip install tox "coverage<=4.0" codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
