language: python
sudo: false
python:
  - 3.6
  - 3.7

before_install:
  - pip install tox poetry

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}" -- py.test tests -v

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
